[package]
name = "prandium"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "3.0.0-beta.5"

reqwest = { version = "0.11", features = ["blocking", "json"] }
select = "0.5.0"

serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
uuid = { version = "0.8", features = ["serde", "v5"] }
sha-1 = "0.9.8"




